version: "3"
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TestDatabase
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306